### ISSUE TITLE
Outline Use Cases

### ISSUE THREAD

**Issue by APettit98** [APettit98/SWE632-Project#1]
Document at least 5 use cases for our application. Each use case must describe a specific user goal and how it can be accomplished using the app. This document will need to be turned in for HW1.

**Comment by mdaly570** [comment]
Here's some use cases for the basic functions of the app. I might embellish these or add more depending on what other functionalities we add:

**U1 - Sort Flights by Timing, Duration, & Price**
- A user can sort flights, once they have selected an origin and destination, by departure/arrival times, flight duration, and price per class, in both ascending and descending order.
- Priority: High
- Actor: Customer, “Database”
- Flow:
	- Basic: Initiated once the customer has selected a flight origin and destination. The system presents the customer a table of available flights for that origin and destination, sorted in ascending order by departure times by default. Using a tab with a group of buttons along the top of the table, the user can customize this sorting. Options include “Departure (Time)”, “Arrival (Time)”, “Duration”, “Price: ‘Economy’, ‘Business’, ‘First’”, and “Ascending” and “Descending”.
- Preconditions: The customer has selected a flight origin and destination.
- Postconditions: The table of available flights is altered according to the chosen sorting method.

**U2 - Filter Flights by Date Range, Price Range, and Airline**
- A user can filter flights, once they have selected an origin and destination, by a user-entered range of dates and prices. Unlike the sorting function, these filters can be enacted simultaneously.
- Priority: High
- Actor: Customer, “Database”
- Flow:
	- Basic: Initiated once the customer has selected a flight origin and destination. The system presents the customer a table of available flights for that origin and destination. Using a tab with a group of drop-down menus and entry fields along the top of the table, the customer can create filters for the list of available flights. These fields include “From (Date)”, “To (Date)”, “Lowest (Price)”, “Highest (Price)”, and “Airline”. For the price range option, one of the three classes must be selected to apply the filter on.
	- Alternate Flow 1: Initiated if the customer makes an invalid entry, or if there are no flights which fit the filter(s) the customer has entered. The system displays an “Error: No flights found” message to the customer, and prompts the customer to choose a different filter(s).
- Preconditions: The customer has selected a flight origin and destination.
- Postconditions: The table of available flights is altered according to the applied filter(s).

**U3 - Browse Flights**
- A user can browse through a list of future flights for a given origin and destination.
- Actor: Customer, “Database”
- Flow:
	- Basic: Initiated once the customer enters the application. The system prompts the customer with two drop-down menus to select an origin and destination city. These menus are fed by the list of cities in the flight “database” (in actuality a static JSON file). Once the user has selected an origin and destination, the system presents the user with a table of all outbound flights over the next week between these points, likewise pulled from the “database”. The user can sort and filter this table as outlined in use cases U1 and U2. Each entry in the table lists the date, origin airport code, destination airport code, airline, departure time, arrival time, duration (in minutes), economy-class price, business-class price, and first-class price for a given flight, and also presents the user with a button which they can click to begin the flight-booking process.
	- Alternative Flow 1: Initiated if there are no flights matching the entered origin and destination points. The system displays an “Error: No flights found” message to the customer, and prompts the customer to enter a different origin and/or destination point.
	- Alternative Flow 2: Initiated if the customer selects a different origin or destination point from the menu after having selected a prior origin and destination. The table of flights updates in real-time to match the new origin and destination.
- Includes: U1, U2
- Preconditions: None
- Postconditions: The table of available flights for the selected origin and destination is displayed.

**U4 - Book a Flight**
- A user can book a flight after choosing it in the browsing menu.
- Actor: Customer
- Flow:
	- Basic: Initiated once the customer clicks the “Book” button next to a desired flight in the flight browsing menu. The system presents the user with a dialog box which restates the details of the selected flight, a drop-down menu to choose the desired class (economy is selected by default), the cost of the flight according to the selected class, an entry field to enter payment information, and buttons to confirm and cancel. Once the customer has selected a class, entered their payment information, and hit the “Confirm” button, a message is displayed to the customer that their flight has been successfully booked. This flight is then visible to the customer on the home page of the application.
	- Alternate Flow 1: Initiated if the customer hits “Confirm” without entering their payment information. The system displays an error message to the user and prompts them to enter their payment information.
	- Alternate Flow 2: Initiated if the customer hits the “Cancel” button in the dialog box. The customer is brought back to the flight browsing menu.
- Preconditions: The customer has selected a flight from the flight browser.
- Postconditions: The booked flight is visible to the customer on the application’s home screen.

**U5 - Cancel a Flight**
- A user can cancel their booking for a flight after they have booked it.
- Actor: Customer
- Flow:
	- Basic: Initiated after the customer has booked a flight(s) and is on the home screen of the application. In the menu listing the customer’s flights, each flight the customer has booked will be displayed in the order they were booked. Next to each flight will be a button giving the customer the option to cancel the flight. Once clicked, the customer will be presented a dialog box listing the details of the flight, as well as a message from the system asking the customer if they are sure they wish to cancel their flight and “Confirm” and “Cancel” buttons. When the customer clicks the “Confirm” button, the system displays a message to the customer confirming the flight’s cancellation, and the flight is removed from the customer’s list of flights on the home screen.
	- Alternate Flow 1: Initiated when the customer clicks the “Cancel” button in the dialog box. The customer is returned to the application’s home screen.
- Preconditions: The customer has already booked at least one flight.
- Postconditions: The canceled flight is no longer visible to the customer on the application’s home screen.
